import Foundation
import Testing
@testable import PapaTodos

/// Expected values were generated by running PapaBoard's own
/// `personColor.js`, `theme.js` and `normalizeAvatarUrl` under Node.
struct PersonColorTests {
    @Test(arguments: [
        ("Mum", 333), ("Dad", 55), ("Fernando De Leon", 234), ("María José", 337),
        ("Unassigned", 231), ("PapaBoard", 108), ("", 108), ("日本語", 143),
        ("a@b.com", 214), ("😀 Kid", 265),
    ])
    func hueMatchesWeb(name: String, expected: Int) {
        #expect(PersonColor.hue(for: name) == expected)
    }

    @Test func nilSeedUsesDefault() {
        #expect(PersonColor.hue(for: nil) == 108)
    }
}

struct ProfileInitialsTests {
    @Test(arguments: [
        ("Fernando De Leon", "FD"), ("Mum", "M"), ("mary-jane.smith", "MJ"),
        ("kid@example.com", "K"), ("  spaced   out  ", "SO"), ("", "PB"), ("@only", "PB"),
    ])
    func matchesWebRules(name: String, expected: String) {
        #expect(ProfileInitials.make(from: name) == expected)
    }

    @Test func nilFallsBackToPB() {
        #expect(ProfileInitials.make(from: nil) == "PB")
    }
}

struct ThemeColorTests {
    @Test(arguments: [
        ("#008F81", "#008F81"), ("008f81", "#008F81"), ("#ffff00", "#FFFF00"),
        (" #abcdef ", "#ABCDEF"),
    ])
    func normalizesValidHex(input: String, expected: String) {
        #expect(ThemeColor.normalize(input) == expected)
    }

    @Test(arguments: ["#fff", "zzz", "", "#12345", "#1234567", "#GGGGGG"])
    func rejectsInvalidHex(input: String) {
        #expect(ThemeColor.normalize(input) == nil)
    }

    @Test func invalidFallsBackToDefault() {
        #expect(ThemeColor.effectiveHex("nope") == ThemeColor.defaultHex)
        #expect(ThemeColor.effectiveHex(nil) == "#008F81")
    }

    /// `true` = white text, matching `getReadableTextColor` on the web.
    @Test(arguments: [
        ("#008F81", false), ("#FFFFFF", false), ("#FFFF00", false), ("#000000", true),
        ("#4F46E5", true), ("#C2410C", true), ("#2F6F46", true), ("#ABCDEF", false),
    ])
    func readableForegroundMatchesWeb(hex: String, whiteText: Bool) {
        #expect(ThemeColor.readableForegroundIsLight(on: hex) == whiteText)
    }

    @Test func everySuggestedColorIsValid() {
        for hex in ThemeColor.suggestedHexes {
            #expect(ThemeColor.normalize(hex) == hex)
        }
    }
}

struct AvatarURLTests {
    @Test(arguments: [
        "https://example.com/a.png", "http://x.co", "https://EXAMPLE.com",
        "https://a.b/?q=1#frag",
    ])
    func acceptsHTTPAndHTTPS(input: String) {
        let parsed = AvatarURL.parse(input)
        #expect(parsed != nil)
        #expect((parsed ?? nil) != nil)
    }

    @Test(arguments: ["ftp://x", "javascript:alert(1)", "notaurl", "https://", "file:///etc/passwd"])
    func rejectsOtherSchemesAndGarbage(input: String) {
        #expect(AvatarURL.parse(input) == nil)
        #expect(!AvatarURL.isValid(input))
    }

    @Test func emptyMeansClear() throws {
        let cleared = try #require(AvatarURL.parse("   "))
        #expect(cleared == nil)
        #expect(AvatarURL.isValid(""))
    }
}
